project_name: ged

before:
  hooks:
    - mkdir -p ged/web/dist/assets
    - cp -r web/dist/. ged/web/dist/

builds:
  - main: .
    dir: ged
    binary: ged
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: darwin
        format: zip

brews:
  - repository:
      owner: squz
      name: homebrew-tap
    homepage: https://github.com/marcelocantos/ge
    description: ge development daemon — serves the dashboard and bridges game servers to mobile players
    license: MIT
    service: |
      run [opt_bin/"ged"]
      keep_alive true
      log_path var/"log/ged.log"
      error_log_path var/"log/ged.log"
