#!/usr/bin/env python3
# Copyright 2026 Marcelo Cantos
# SPDX-License-Identifier: Apache-2.0
#
# wire-icons.py — idempotently patch a consuming project's iOS and
# Android sources so the app-icon assets generated by ge-icon-gen
# (Assets.xcassets/, res/mipmap-*, etc.) are actually picked up by the
# native build.
#
# Three patches:
#   1. ios/Info.plist            — ensure <key>CFBundleIconName</key>
#                                   <string>AppIcon</string>.
#   2. ios/CMakeLists.txt        — ensure the Assets.xcassets target_sources
#                                   block referenced by the iOS template.
#   3. android/.../AndroidManifest.xml
#                                — ensure android:icon and android:roundIcon
#                                   on the <application> element.
#
# Each patch is a no-op if the wiring is already present. Regex-based,
# not XML-parsed, so the script preserves the project's existing
# formatting (comments, attribute order, indentation) byte-for-byte
# wherever it doesn't need to touch anything.
#
# Invoked from `make ge/app-icons` after icon assets are generated.

import argparse
import re
import sys
from pathlib import Path


def patch_info_plist(path: Path) -> bool:
    """Insert <key>CFBundleIconName</key><string>AppIcon</string> before the
    root </dict> if absent. Returns True if the file was modified."""
    if not path.is_file():
        print(f"wire-icons: skipping iOS Info.plist (not found): {path}",
              file=sys.stderr)
        return False
    text = path.read_text()
    if "<key>CFBundleIconName</key>" in text:
        return False
    # Insert before the LAST </dict> (root dict closing tag) to be safe in
    # case the plist has nested dicts.
    idx = text.rfind("</dict>")
    if idx < 0:
        print(f"wire-icons: malformed plist (no </dict>): {path}",
              file=sys.stderr)
        return False
    line_start = text.rfind("\n", 0, idx) + 1
    # Pick up the indent from the nearest preceding <key> tag so the
    # insert matches the surrounding style. The closing </dict> often
    # sits at column 0 even when keys are indented (4 spaces is the
    # Apple-Xcode default), so copying its indent would produce a
    # ragged edit.
    sample = re.search(r"^(\s*)<key>", text[:line_start], re.MULTILINE)
    indent = sample.group(1) if sample else ""
    insertion = (f"{indent}<key>CFBundleIconName</key>\n"
                 f"{indent}<string>AppIcon</string>\n")
    new_text = text[:line_start] + insertion + text[line_start:]
    path.write_text(new_text)
    print(f"wire-icons: patched {path} (added CFBundleIconName)")
    return True


# CMake snippet to inject — mirrors the iOS template's app-icon block.
# Placeholder __TARGET__ is replaced with the consuming project's target
# name (auto-detected from add_executable).
_CMAKE_BLOCK = """
# ── App-icon asset catalog (added by ge/wire-icons) ─────────────────────
# Populated by `make ge/app-icons`. CFBundleIconName=AppIcon in Info.plist
# tells Xcode which catalog entry resolves the icon at install time.
set(APP_ICON_XCASSETS "${CMAKE_CURRENT_SOURCE_DIR}/Assets.xcassets")
if(EXISTS "${APP_ICON_XCASSETS}")
    target_sources(__TARGET__ PRIVATE "${APP_ICON_XCASSETS}")
    set_source_files_properties("${APP_ICON_XCASSETS}" PROPERTIES
        MACOSX_PACKAGE_LOCATION "Resources")
    set_target_properties(__TARGET__ PROPERTIES
        XCODE_ATTRIBUTE_ASSETCATALOG_COMPILER_APPICON_NAME "AppIcon")
endif()
"""


def patch_cmakelists(path: Path) -> bool:
    """Append the Assets.xcassets target_sources block to an iOS CMakeLists
    if absent. Returns True if modified."""
    if not path.is_file():
        print(f"wire-icons: skipping iOS CMakeLists (not found): {path}",
              file=sys.stderr)
        return False
    text = path.read_text()
    if "APP_ICON_XCASSETS" in text:
        return False
    # Auto-detect the executable target name from add_executable(<name> ...).
    m = re.search(r"^[ \t]*add_executable\(\s*([A-Za-z_][A-Za-z0-9_-]*)\b",
                  text, re.MULTILINE)
    if not m:
        print(f"wire-icons: cannot find add_executable() in {path} — "
              "leaving CMakeLists untouched", file=sys.stderr)
        return False
    target = m.group(1)
    block = _CMAKE_BLOCK.replace("__TARGET__", target)
    new_text = text.rstrip() + "\n" + block
    path.write_text(new_text)
    print(f"wire-icons: patched {path} (added Assets.xcassets block "
          f"for target '{target}')")
    return True


def patch_android_manifest(path: Path) -> bool:
    """Ensure android:icon and android:roundIcon attributes on the
    <application> element. Returns True if modified."""
    if not path.is_file():
        print(f"wire-icons: skipping AndroidManifest (not found): {path}",
              file=sys.stderr)
        return False
    text = path.read_text()
    # Find the <application ... > opening tag (may span multiple lines).
    m = re.search(r"<application\b([^>]*?)(/?>)", text, re.DOTALL)
    if not m:
        print(f"wire-icons: no <application> tag in {path}",
              file=sys.stderr)
        return False
    attrs_text, close = m.group(1), m.group(2)
    new_attrs = attrs_text
    changed = False
    if "android:icon=" not in attrs_text:
        new_attrs = new_attrs.rstrip() + \
                    '\n        android:icon="@mipmap/ic_launcher"'
        changed = True
    if "android:roundIcon=" not in attrs_text:
        new_attrs = new_attrs.rstrip() + \
                    '\n        android:roundIcon="@mipmap/ic_launcher_round"'
        changed = True
    if not changed:
        return False
    new_tag = f"<application{new_attrs}{close}"
    new_text = text[:m.start()] + new_tag + text[m.end():]
    path.write_text(new_text)
    print(f"wire-icons: patched {path} "
          f"(added android:icon / android:roundIcon)")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Idempotently patch consumer project files to pick up "
                    "the ge-icon-gen output.")
    ap.add_argument("--ios-info-plist",
                    type=Path, default=Path("ios/Info.plist"),
                    help="Path to ios/Info.plist (default: ios/Info.plist)")
    ap.add_argument("--ios-cmakelists",
                    type=Path, default=Path("ios/CMakeLists.txt"),
                    help="Path to ios/CMakeLists.txt "
                         "(default: ios/CMakeLists.txt)")
    ap.add_argument("--android-manifest",
                    type=Path,
                    default=Path("android/app/src/main/AndroidManifest.xml"),
                    help="Path to AndroidManifest.xml")
    args = ap.parse_args()

    any_change = False
    any_change |= patch_info_plist(args.ios_info_plist)
    any_change |= patch_cmakelists(args.ios_cmakelists)
    any_change |= patch_android_manifest(args.android_manifest)
    if not any_change:
        print("wire-icons: nothing to do (project already wired)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
